<?php

function submitted_info_field_extra_fields()
{
  $extra = [];

  $field = [
    'submitted_info' => [
      'label' => t('Submitted info'),
      'description' => t('Submitted information.'),
      'weight' => 0,
      'visible' => false,
    ],
  ];

  foreach (node_type_get_types() as $type) {
    $extra['node'][$type->type]['display'] = $field;
  }

  return $extra;
}

function submitted_info_node_view($node, $view_mode)
{
  $extra_fields = field_extra_fields_get_display('node', $node->type, $view_mode);

  if (isset($extra_fields['submitted_info']['visible']) && $extra_fields['submitted_info']['visible']) {
    $node->content['submitted_info'] = [
      '#field_name' => 'submitted_info',
      '#markup' => theme('submitted_info', [
        'node' => $node
      ]),
      '#weight' => $extra_fields['submitted_info']['weight'],
    ];
  }
}

function submitted_info_theme()
{
  return [
    'submitted_info' => [
      'arguments' => [
        'node' => NULL
      ],
    ],
  ];
}

function theme_submitted_info($variables)
{
  $node = $variables['node'];

  return '<p class="submitted-info">' .
    t('Submitted by @author on @created', [
      '@author' => $node->name,
      '@created' => format_date($node->created, 'custom', 'j F Y'),
    ]) . '</p>';
}
